from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict


class ProductBase(BaseModel):
    """Base fields for Product schema."""
    name: str = Field(..., min_length=1, max_length=255, description="Product item name")
    category: Optional[str] = Field("General", max_length=100)
    description: Optional[str] = Field(None)
    sku: Optional[str] = Field(None, max_length=100, description="SKU identifier (autogenerated if not provided)")


class ProductCreate(ProductBase):
    """Schema for creating a product."""
    buying_price: Optional[float] = Field(0.0, ge=0.0)
    selling_price: Optional[float] = Field(0.0, ge=0.0)
    current_stock: Optional[int] = Field(0, ge=0)
    minimum_stock: Optional[int] = Field(5, ge=0)
    maximum_stock: Optional[int] = Field(100, ge=0)
    supplier_id: Optional[int] = Field(None)
    expiry_date: Optional[datetime] = Field(None)


class ProductUpdate(BaseModel):
    """Schema for updating a product."""
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    sku: Optional[str] = Field(None, max_length=100)
    category: Optional[str] = Field(None, max_length=100)
    description: Optional[str] = Field(None)


class ProductResponse(BaseModel):
    """Schema for returning product data."""
    id: int
    business_id: int
    sku: str
    name: str
    category: Optional[str] = "General"
    description: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
